id: P005411
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16651
  title: གསུང་འབུམ། གོ་རམས་པ་བསོད་ནམས་སེངྒེ།
  author: ''
  volumes:
    bd1aaf43bf8a488788900ff1a8e34b8e:
      image_group_id: I2PD17674
      title: ''
      volume_number: 1
      total_pages: 604
    ce62832e31774d2e8a30ce4eeee7fc6d:
      image_group_id: I2PD17675
      title: ''
      volume_number: 2
      total_pages: 522
    9b98a78dbd49498bbd8d9fd2785c691e:
      image_group_id: I2PD17676
      title: ''
      volume_number: 3
      total_pages: 494
    be0fb28a894d4724b3d347a8e4b9b022:
      image_group_id: I2PD17677
      title: ''
      volume_number: 4
      total_pages: 514
    1e5f1386993e4cd9bf6bd32a3c92bfc6:
      image_group_id: I2PD17678
      title: ''
      volume_number: 5
      total_pages: 540
    d260cee8b74e41bd96548beab11bc5f7:
      image_group_id: I2PD17679
      title: ''
      volume_number: 6
      total_pages: 458
    ab77325bc9ef466f8f6e71392305eba4:
      image_group_id: I2PD17680
      title: ''
      volume_number: 7
      total_pages: 434
    617d2408decf4bfca574cbaba5fe793c:
      image_group_id: I2PD17681
      title: ''
      volume_number: 8
      total_pages: 444
    21aaf349b9944029ae4500f3a884365d:
      image_group_id: I2PD17682
      title: ''
      volume_number: 9
      total_pages: 546
    d91d119a36f94b6db2dfac95c6b9f073:
      image_group_id: I2PD17683
      title: ''
      volume_number: 10
      total_pages: 482
    05420ccee8364555b8e2beee653e5a68:
      image_group_id: I2PD17684
      title: ''
      volume_number: 11
      total_pages: 398
    95d0d5aeda06434c84a1a68b07458e53:
      image_group_id: I2PD17685
      title: ''
      volume_number: 12
      total_pages: 510
    33c1fdd5742a4cb2a2faccc1e0231775:
      image_group_id: I2PD17686
      title: ''
      volume_number: 13
      total_pages: 494
    b5ca3f11d9a24fc18bb686f3a700b66f:
      image_group_id: I2PD17687
      title: ''
      volume_number: 14
      total_pages: 480
    8917821a4bd641469a7b91bbd90530ca:
      image_group_id: I2PD17688
      title: ''
      volume_number: 15
      total_pages: 526
